arklian/patina

personal/amanda/js/.eslintrc.cjs, personal/amanda/js/README.md, personal/amanda/js/index.html, personal/amanda/js/package.json, personal/amanda/js/pnpm-lock.yaml, personal/amanda/js/src/App.css, personal/amanda/js/src/App.tsx, personal/amanda/js/src/index.css, personal/amanda/js/src/main.tsx, personal/amanda/js/src/vite-env.d.ts, personal/amanda/js/tsconfig.json, personal/amanda/js/tsconfig.node.json, personal/amanda/js/vite.config.ts
Completed the Part 1 React exercises from Fullstack Open
=> Amanda: Fullstack Open React Exercises

personal/kazi/js/.eslintrc.cjs, personal/kazi/js/README.md, personal/kazi/js/index.html, personal/kazi/js/package.json, personal/kazi/js/pnpm-lock.yaml, personal/kazi/js/src/App.css, personal/kazi/js/src/App.tsx, personal/kazi/js/src/index.css, personal/kazi/js/src/main.tsx, personal/kazi/js/src/vite-env.d.ts, personal/kazi/js/tsconfig.json, personal/kazi/js/tsconfig.node.json, personal/kazi/js/vite.config.ts
Kazi: Pull Request
Adding in Kazi's personal page with exercises from fullstackopen
=> Kazi: Pull Request

js/src/Router.tsx, js/src/personal/amanda/Amanda.module.css, js/src/personal/amanda/Amanda.page.tsx
Created a new page on the website.
=> Amanda: Create page on website

js/src/Router.tsx, js/src/personal/bryan/Bryan.module.css, js/src/personal/bryan/Bryan.page.tsx
Created a Bryan.page.tsx and Bryan.module.css file as the base page setup, as well as changed Router.tsx to add my page as a possible option to go to.
=> Bryan: Adding in base code for personal page

js/src/Router.tsx, js/src/personal/kazi/Kazi.module.css, js/src/personal/kazi/Kazi.page.tsx
Added files and an option to go to Kazi's personal website.
=> Kazi: Added personal website option

js/src/Router.tsx, js/src/personal/Manny/Manny.module.css, js/src/personal/Manny/Manny.page.tsx
Manny: setting up my personal page, just changing the name
=> Manny: setting up my personal page

js/src/Router.tsx, js/src/personal/_maliha/Maliha.module.css, js/src/personal/_maliha/Maliha.page.tsx
Maliha: start personal website
=> Maliha: adding personal website

js/src/Router.tsx, js/src/personal/_jionghao/Jionghao.module.css, js/src/personal/_jionghao/Jionghao.page.tsx
=> Jionghao: created personal page

js/src/Router.tsx, js/src/personal/kelly/Kelly.module.css, js/src/personal/kelly/Kelly.page.tsx
=> Personal Website

js/src/Router.tsx, js/src/personal/riyuan/Riyuan.module.css, js/src/personal/riyuan/Riyuan.page.tsx
=> riyuan: starting the personal_web

js/src/Router.tsx, js/src/personal/tony/Tony.module.css, js/src/personal/tony/Tony.page.tsx
Added Tony.module.css and Tony.page.tsx
Changed Router.tsx to go be able to go to my page
=> Tony: Added personal website

js/src/Router.tsx, js/src/personal/jionghao/Jionghao.page.tsx
Changed component to following react component naming convention
=> Jionghao: Updated React component

js/src/Router.tsx, js/src/personal/tony/Tony.page.tsx
used prettier to auto format code
=> Tony: auto formatted code with prettier

js/src/personal/bryan/Bryan.page.tsx, js/src/personal/bryan/TimeDisplay.tsx
Added a base time/date functionality (replacing old Welcome to Bryan's Page title)
L=ENG-41
=> Bryan: Added time functionality to my website

js/src/personal/amanda/Amanda.main.page.tsx, js/src/personal/amanda/Amanda.module.css, js/src/personal/amanda/Amanda.page.tsx
I created the landing page and a general layout of the main page.
=> Amanda: Create landing page for website

js/src/personal/kelly/Kelly.module.css, js/src/personal/kelly/Kelly.page.tsx
Updated website elements 1.0, removed original mantine template
=> Kelly: updated title and fonts

js/package.json, js/pnpm-lock.yaml, js/src/personal/jionghao/FooterSocial.module.css, js/src/personal/jionghao/FooterSocial.tsx, js/src/personal/jionghao/Jionghao.module.css, js/src/personal/jionghao/Jionghao.page.tsx
Implemented button for light/dark modes
and started a footer for social medias
L=ENG-71
=> Jionghao: Added button to switch light/dark modes

js/src/personal/bryan/Bryan.module.css, js/src/personal/bryan/Bryan.page.tsx, js/src/personal/bryan/LightDark.tsx, js/src/personal/bryan/Settings.tsx, js/src/personal/bryan/TimeDisplay.tsx
Added in a button on top-right corner called settings. Inside, currently have a modified version of the light/dark button provided in components (as a separate file). Also includes minor nit changes from previous pull request
L=ENG-28
L=ENG-29
=> Bryan: Created settings menu, light/dark mode, started navbar

js/src/personal/tony/Tony.module.css, js/src/personal/tony/Tony.page.tsx
Tony: Added Page layout and image
Added react icons library to make social buttons that link
to socials.
Split up page into 2 grids, left side with name and image
right side with temporary paragraph for about me.
Expanded grid to fit entire viewport.
L=ENG-24
L=ENG-73
L=ENG-86
=> Tony: Created page layout, added image and social buttons

js/src/personal/bryan/Bryan.module.css, js/src/personal/bryan/Bryan.page.tsx, js/src/personal/bryan/LightDark.tsx, js/src/personal/bryan/Settings.tsx, js/src/personal/bryan/Status.tsx, js/src/personal/bryan/TimeDisplay.tsx
Changed font to inconsolidata, monospace, as well as added blinking
colon and weekday not in TimeDisplay. Added status that works based on
weekday and time of display.
L=ENG-42
=> Bryan: Changed font/TimeDisplay; Added Status

js/src/personal/haoking/Haoking.module.css, js/src/personal/haoking/Haoking.page.tsx, js/src/personal/haoking/LeftAboutMe.tsx, js/src/personal/haoking/RightAboutMe.tsx, js/src/personal/haoking/Time.tsx, js/src/personal/haoking/theme.ts
Created a timer component displaying the current time, created a spotify song embed, inserted both into home page. Refactored code from main page's file into a leftbox, rightbox, time components. Not associated with any Linear issues.
=> Haoking: Embed spotify, timer component, refactor

js/src/personal/bryan/Bryan.page.tsx, js/src/personal/bryan/NavBar.tsx, js/src/personal/bryan/Settings.tsx, js/src/personal/bryan/Socials.tsx
Currently only has placeholder links/names
L=ENG-32
=> Bryan: Added in base social media footer

js/src/personal/amanda/Amanda.module.css, js/src/personal/amanda/Contact.tsx, js/src/personal/amanda/Data.json, js/src/personal/amanda/Main.page.tsx, js/src/personal/amanda/Navbar.tsx, js/src/personal/amanda/Section.tsx, js/src/personal/amanda/theme.ts
<fixes L={ENG-91, ENG-92, ENG-98}>
The font style has been changed from the default font and the navbar is updated to show which section the user is at. The contact section is also updated with icons and placeholder links.
=> Amanda: Changed styling and included icons

js/src/Routes.tsx, js/src/personal/bryan/AboutMe.page.tsx, js/src/personal/bryan/Bryan.page.tsx, js/src/personal/bryan/Fun.page.tsx, js/src/personal/bryan/Main.page.tsx, js/src/personal/bryan/Projects.page.tsx
Using children parameter of routers, now can create subpages. Currently
still have main page as primary path (/bryan) Also have about me, fun,
and project page built from small parts of main page
L=ENG-100
=> Bryan: Added routing system to allow for subpages

js/src/personal/bryan/AboutMe.page.tsx, js/src/personal/bryan/Bryan.module.css, js/src/personal/bryan/Bryan.page.tsx, js/src/personal/bryan/DateDisplay.tsx, js/src/personal/bryan/Fun.page.tsx, js/src/personal/bryan/Main.page.tsx, js/src/personal/bryan/NavBar.tsx, js/src/personal/bryan/Projects.page.tsx, js/src/personal/bryan/Socials.tsx, js/src/personal/bryan/TimeDisplay.tsx
Updated links to go from page to page in header; updated footer to be
in the bottom (rather than hanging at bottom of components)
L=ENG-120
=> Bryan: Updated Header/Footer framework

js/src/personal/kazi/Kazi.module.css, js/src/personal/kazi/Kazi.page.tsx, js/src/personal/kazi/components/DarkModeToggle/DarkModeToggle.module.css, js/src/personal/kazi/components/DarkModeToggle/DarkModeToggle.tsx, js/src/personal/kazi/components/Navbar/Navbar.module.css, js/src/personal/kazi/components/Navbar/Navbar.tsx
=> Kazi: Creation of Navbar

js/src/personal/tony/Tony.module.css, js/src/personal/tony/Tony.page.tsx
Used a black and white color palette. Added experience and projects with description. Changed font sizes and weights. Changed location of icon buttons. Added flashlight effect for mouse moving around the page.
L=ENG95
L=ENG110
L=ENG128
=> Tony: Changed color palette and added content

js/src/personal/haoking/Haoking.module.css, js/src/personal/haoking/Haoking.page.tsx, js/src/personal/haoking/aboutme/AboutMe.tsx, js/src/personal/haoking/aboutme/LeftAboutMe.tsx, js/src/personal/haoking/aboutme/RightAboutMe.tsx, js/src/personal/haoking/components/NavLink.tsx, js/src/personal/haoking/components/Navbar.tsx, js/src/personal/haoking/components/Time.tsx, js/src/personal/haoking/misc/MiscPage.tsx, js/src/personal/haoking/pages.ts, js/src/personal/haoking/projects/LeftProjects.tsx, js/src/personal/haoking/projects/ProjectsPage.tsx, js/src/personal/haoking/projects/RightProjects.tsx
Added a functioning navbar that renders different placeholder pages. Added a fade in animation to components of each page. Created placeholder projects page and miscellaneous page. 
L=ENG-38
L=ENG-99
=> Haoking: Functioning navbar, fade-in animation

js/src/personal/bryan/AboutMe/AboutMeText.tsx, js/src/personal/bryan/Fun/Fun.module.css, js/src/personal/bryan/Fun/Fun.page.tsx, js/src/personal/bryan/Projects/Projects.module.css, js/src/personal/bryan/Projects/Projects.page.tsx
Built base structure that I want fun page to be like. Created css file for fun page as well.
L=ENG-103
=> Bryan: Created Fun Page Framework

js/src/personal/kazi/Kazi.module.css, js/src/personal/kazi/Kazi.page.tsx, js/src/personal/kazi/components/Navbar/Navbar.module.css, js/src/personal/kazi/components/Navbar/Navbar.tsx
Changed css files to no longer affect globally
=> Kazi: Fixed nits and global css changes

js/src/personal/bryan/AboutMe/AboutMe.module.css, js/src/personal/bryan/AboutMe/AboutMePictures.tsx, js/src/personal/bryan/Bryan.module.css, js/src/personal/bryan/Bryan.page.tsx, js/src/personal/bryan/Frame/TimeDisplay.tsx, js/src/personal/bryan/Fun/Fun.module.css, js/src/personal/bryan/Fun/Fun.page.tsx, js/src/personal/bryan/Projects/Projects.module.css, js/src/personal/bryan/Projects/Projects.page.tsx
Moved clock to top-right and shifted things up/down. Filled fun
page with a bit of content. Updated css files
L=ENG-129
=> Bryan: Reworked fun page/moved clock/footer

js/src/personal/tony/Tony.module.css, js/src/personal/tony/Tony.page.tsx
Created project section and added link to project. Added links for experience section as well. Changed some spacing and css. Fixed flashlight not going down when scrolling.
L=ENG-111
=> Tony: Added project section with links

js/src/personal/jionghao/Jionghao.page.tsx, js/src/personal/jionghao/components/About.module.css, js/src/personal/jionghao/components/Experience.module.css, js/src/personal/jionghao/components/Experience.tsx, js/src/personal/jionghao/components/Header.module.css, js/src/personal/jionghao/components/Hero.module.css, js/src/personal/jionghao/components/Work.module.css, js/src/personal/jionghao/components/Work.tsx
=> Jionghao: Add Experience section

js/src/personal/maliha/About.tsx, js/src/personal/maliha/Fonts.tsx, js/src/personal/maliha/Images.tsx, js/src/personal/maliha/Maliha.module.css, js/src/personal/maliha/Maliha.page.tsx, js/src/personal/maliha/ModalMenu.tsx, js/src/personal/maliha/Sandwich.tsx, js/src/personal/maliha/Social.tsx, js/src/personal/maliha/Spotify.tsx
=> Maliha: Created about me page

js/src/Router.tsx, js/src/Routes.tsx, js/src/patina/Patina.page.tsx, js/src/patina/PatinaWelcome.module.css, js/src/patina/PatinaWelcome.tsx, js/src/patina/theme.ts, js/src/personal/PersonalRoutes.tsx, js/src/personal/bryan/BryanRoutes.tsx
Modified routing system and welcome page so that now, our personal
websites are hosted in /private/{name}.
L=ENG-170
Change-Id: Ib6b2052b7c72865f4af4797e858eb0a6f913bace
=> Bryan: Updated routing system

.github/workflows/example-action.yml, .github/workflows/pass.json
Change-Id: I005d1b3d489b8604e3235c649cfd682cc5aedf71
=> Amanda: Add link to message

js/src/patina/components/Footer.module.css
Change-Id: I0d3eebe0b0ff4fbca4245896c029816e05ecd503
=> PatNet: Fix footer to properly adapt web and mobile view

js/src/patina/pages/home/about/About.tsx
- made the button text less bold
- when the button is clicked it takes the user to the mission page
Change-Id: I704f3f7be8167ab4620cfdd3ff9445d2e88286bb
=> HomePage: Apply fix to Button on Home Screen

js/src/personal/jionghao/components/About.module.css, js/src/personal/jionghao/components/About.tsx, js/src/personal/jionghao/components/Hero.module.css, js/src/personal/jionghao/components/Hero.tsx
TEST=manual
ran locally and worked
Change-Id: Ib403401d1d4a84f02c4d213d83e69965e363ef0a
=> Jionghao: Add fade-in animation to about section

db/sqitch.conf, docs/sqitch.md
added target for local dev
Change-Id: I135b925fe99d4aa74985cba7aaa77fcf7efc2c63
=> Sqitch: Added patina db shortcut

js/src/patina/assets/images.ts, js/src/patina/pages/about/team/teamData.ts, js/src/patina/pages/community/Community.page.tsx, js/src/patina/pages/internship/internData.ts, js/src/patina/pages/mentor/about/About.tsx
Updated links and fixed wording for pages.
TEST=manual
- Checked website to see changes
Change-Id: I217f0c69e507cd87203230c95e30dfb1b3bee7d7
=> Website: Overall website fixes

js/src/patina/assets/images.ts, js/src/patina/pages/about/team/teamData.ts, js/src/patina/pages/community/Community.page.tsx, js/src/patina/pages/internship/FractalBadge.module.css, js/src/patina/pages/internship/FractalBadge.tsx, js/src/patina/pages/internship/internData.ts, js/src/patina/pages/mentor/about/About.tsx
TEST=manual
fractalWebsite.png: https://patina-dev.nyc3.digitaloceanspaces.com/screenshot/Screenshot-2024-08-15T19:05:42-AmandaRuan-fractalWebsite.png
fractalMobile.png: https://patina-dev.nyc3.digitaloceanspaces.com/screenshot/Screenshot-2024-08-15T19:06:49-AmandaRuan-fractalMobile.png
Change-Id: Id212b9ee7711519dddf4fe89725b8df842fb41c3
=> Internship: Fix layout of Fractal banner and text

js/src/patina/pages/internship/Internship.page.tsx, js/src/patina/pages/internship/MentorCard.module.css, js/src/patina/pages/internship/MentorCard.tsx, js/src/patina/pages/internship/internshipData.ts
Changed wording on page and added mentors section.
TEST=manual
- Checked website for layout
internshipMentorCards.png: https://patina-dev.nyc3.digitaloceanspaces.com/screenshot/Screenshot-2024-08-15T20:50:49-AmandaRuan-internshipMentorCards.png
Change-Id: Iece8695883fe41f5568a18314c09f126099981ad
=> Internship: Update layout based on Figma

.github/workflows/README.md, tools/git/commands/git-up
TEST=none
Change-Id: I228cd0f4c90aca0682f9a7e69636320928f3b990
=> Documentation: Update documentation on workflows

js/src/personal/martin/about/About.page.tsx, js/src/personal/martin/data.json, js/src/personal/martin/main/Main.page.tsx
Exported data from main and about pages to the data.json file. All
large blocks of text have been removed from main and about for code
readability.
TEST=manual
Ran prt, no errors
Change-Id: I54a4d45ba031bd0d6da4ca338178212525acd6c7
=> Martin: Update data.json

js/src/patina/pages/blog/Blog.module.css, js/src/patina/pages/blog/FocusedBlog.module.css, js/src/patina/pages/blog/ImageCard.module.css, js/src/patina/pages/blog/ImageCard.tsx, src/test/java/org/patinanetwork/patinawebsite/blogs/BlogsListOpTest.java
Some things could be fixed more.
TEST=manual
Change-Id: I6fccd645cc4fa4e42ae79398901a81e8f432844b
=> Blog: Minor blog css changes

db/sqitch.conf, docs/postgres-on-docker.md, src/main/resources/application.properties
Change-Id: I73aed93d00f3d7f81c0b8f1f3eec548e1194ad1d
=> Docs: Update postgres-on-docker readme

js/src/patina/pages/blog/Blog.page.tsx, src/main/java/org/patinanetwork/patinawebsite/blogs/BlogsController.java, src/main/java/org/patinanetwork/patinawebsite/blogs/repo/PsqlBlogsRepo.java
Added a new getRecentBlogs endpoint to get the 2 actual most recent
blogs separate from allBlogs displayed on each page.
TEST=manual
Ran the page locally to validate features.
Change-Id: I7dad3fe093589289239f82b20f3b0734d3961215
=> Blogs: Add getRecentBlogs endpoint

js/package.json, js/pnpm-lock.yaml, js/src/patina/admin/blog/AdminBlog.page.tsx, js/src/patina/admin/blog/BlogDataTable.tsx
Created an edit section and installed mantine DataTable to display blogs
from the database. Hard coded two blog examples into the data table.
TEST=manual
Ran page locally to verify feature works
Change-Id: Ied70501dfd96e2a278b51104eaa6db29d99fa8cf
=> AdminBlog: Added Edit section with DataTable

js/src/personal/manny/Manny.page.tsx, js/src/personal/manny/sections/About.module.css, js/src/personal/manny/sections/About.tsx
- Added a blur about about my self
- Added icons of languages and skills i know
- This is more like a skeleton since it doesn't have
pictures
Test= manual
Mannyaboutsection.png: https://patina-dev.nyc3.digitaloceanspaces.com/screenshot/Screenshot-2024-08-28T07:22:27-MReyes1241-Mannyaboutsection.png
Change-Id: Ifddf7a0b477875d64398f9cb71e97a17541339a9
=> Manny: Add about section to website

js/src/personal/manny/Manny.page.tsx, js/src/personal/manny/sections/About.module.css, js/src/personal/manny/sections/About.tsx
- Added a section to showcase a little more personality
- This section is still incomplete since it still needs
the images
Test= Manual
MannyaboutsectionMore.png: https://patina-dev.nyc3.digitaloceanspaces.com/screenshot/Screenshot-2024-08-28T18:41:04-MReyes1241-MannyaboutsectionMore.png
Change-Id: I716eb11a9a0619c9f5d5713a3a69f9e6eca1d25e
=> Manny: Add more about me section

js/src/patina/pages/mentor/Mentor.page.tsx, js/src/patina/pages/mentorship/Mentorship.page.tsx
Streamlined the forms to sign up.
TEST=manual
Apply buttons on each page lead to the right form.
Change-Id: I3d40573f4f40db078711c6d935ab17f2b4d28bc0
=> Mentorship: Updated Google Forms links

js/src/patina/pages/mentorship/Mentorship.page.tsx, js/src/patina/pages/mentorship/about/About.tsx
TEST=manual
Change-Id: I15656833ab680d1b48b37dd8c891ef9d168e805f
=> Mentorship: Update text in hero

js/build.gradle.kts, js/src/patina/pages/mentorship/Mentorship.page.tsx, js/src/patina/pages/mentorship/about/About.tsx
Excluding them through gradle.
TEST=manual
Change-Id: Ic1548fa16516bc8fad2e9307e0e03ecd72ca2ecb
=> IntelliJ: Exclude unused JS files

js/build.gradle.kts, js/src/patina/pages/mentorship/Mentorship.page.tsx, js/src/patina/pages/mentorship/about/About.module.css, js/src/patina/pages/mentorship/about/About.tsx, js/src/patina/pages/mentorship/gain/Gain.tsx, js/src/patina/pages/mentorship/program/ProgramDetails.module.css, js/src/patina/pages/mentorship/program/ProgramDetails.tsx
Now that we've solidified more the programming, adding details to the
page for mentees.
TEST=manual
Tested locally on both desktop and mobile
Did a extra read over the text as well.
Change-Id: Ibee86cb50dabb4e79cd0b6ecc36266c05bac5b89
=> Mentorship: Add concrete program details

js/build.gradle.kts, js/src/patina/pages/mentor/Mentor.page.tsx, js/src/patina/pages/mentor/about/About.module.css, js/src/patina/pages/mentor/about/About.tsx, js/src/patina/pages/mentor/program/ProgramDetails.module.css, js/src/patina/pages/mentor/program/ProgramDetails.tsx, js/src/patina/pages/mentorship/Mentorship.page.tsx, js/src/patina/pages/mentorship/about/About.module.css, js/src/patina/pages/mentorship/about/About.tsx, js/src/patina/pages/mentorship/gain/Gain.tsx, js/src/patina/pages/mentorship/program/ProgramDetails.module.css, js/src/patina/pages/mentorship/program/ProgramDetails.tsx, js/src/patina/theme.ts
Per Celina, we should just go with white.
TEST=manual
Change-Id: If32f27403ecbeff37866a06d9d41ff189735cbe6
=> Patina: Update base text color to be white

js/build.gradle.kts, js/src/patina/pages/mentor/Mentor.page.tsx, js/src/patina/pages/mentor/about/About.module.css, js/src/patina/pages/mentor/about/About.tsx, js/src/patina/pages/mentor/program/ProgramDetails.module.css, js/src/patina/pages/mentor/program/ProgramDetails.tsx, js/src/patina/pages/mentorship/Mentorship.page.tsx, js/src/patina/pages/mentorship/about/About.module.css, js/src/patina/pages/mentorship/about/About.tsx, js/src/patina/pages/mentorship/gain/Gain.tsx, js/src/patina/pages/mentorship/program/ProgramDetails.module.css, js/src/patina/pages/mentorship/program/ProgramDetails.tsx
Adding details now that they've been decided on.
Most of the items are duplicated from the mentorship page, with
mentee changed to mentor.
TEST=manual
Tested locally on desktop and mobile
Did a pass on the text
Change-Id: If1c765ddac54ea99c7c241b5ed6b35221ccb0a38
=> Mentor: Add concrete program details

js/src/personal/manny/Manny.page.tsx, js/src/personal/manny/components/HeaderSimple.tsx, js/src/personal/manny/sections/Projects.module.css, js/src/personal/manny/sections/Projects.tsx
- Added a project section that highlights all the project i
have done thus far with a little description
- The project also include buttons to direct the user to either
more info or to a live demo, not all projects include both buttons
- The section is still incomplete
Test= manual
mannyProjectSection.png: https://patina-dev.nyc3.digitaloceanspaces.com/screenshot/Screenshot-2024-08-29T19:06:10-MReyes1241-mannyProjectSection.png
Change-Id: I356216e81925cde6e9615daec6d5bef96f488150
=> Manny: Add project section to page

js/src/personal/manny/Manny.page.tsx, js/src/personal/manny/components/HeaderSimple.tsx, js/src/personal/manny/sections/Projects.module.css, js/src/personal/manny/sections/Projects.tsx
- Adding a simple title to the project section to maintain the
layout
Test= manual
mannyProjectSectionTitle.png: https://patina-dev.nyc3.digitaloceanspaces.com/screenshot/Screenshot-2024-08-29T21:39:40-MReyes1241-mannyProjectSectionTitle.png
Change-Id: Ia9356bacb4731959ae279f7871403cd6ab5db263
=> Manny: Add title to project section

js/src/personal/manny/Manny.page.tsx, js/src/personal/manny/components/HeaderSimple.tsx, js/src/personal/manny/sections/Projects.module.css, js/src/personal/manny/sections/Projects.tsx
- the user can now hover over and click on the images associated with
the projects and be take to see either a live demo or more info
Test= manual
Change-Id: I3fcc110ca7a17865a7ecc909a6ac677c2d6d8669
=> Manny: Update Project section

js/src/patina/Patina.routes.tsx, js/src/patina/navbar/NavBar.tsx, js/src/patina/pages/home/initiatives/Initiatives.tsx
We're not likely to run a scholarship anytime soon. Removing it from
our website.
TEST=manual
Change-Id: I4ed4d6f9c9aa00b2f62122355a26f649d4f966c7
=> Scholarship: Hide scholarship navigation

js/src/patina/Patina.routes.tsx, js/src/patina/navbar/NavBar.tsx, js/src/patina/pages/home/initiatives/Initiatives.tsx, js/src/patina/pages/mentor/program/ProgramDetails.tsx, js/src/patina/pages/mentorship/Mentorship.page.tsx, js/src/patina/pages/mentorship/program/ProgramDetails.tsx
TEST=manual
Change-Id: Ib0c462aa1aae5c5f91845ed4d4cadefe03968e53
=> Mentorship: Fix dates and close applications

gradle/wrapper/gradle-wrapper.properties, js/src/patina/Patina.routes.tsx, js/src/patina/admin/event/AdminEvent.page.tsx, js/src/patina/admin/event/EditEvent.tsx, js/src/patina/navbar/NavBar.tsx, js/src/patina/pages/home/initiatives/Initiatives.tsx, js/src/patina/pages/home/involved/GetInvolved.tsx
Small front end change that adds space for a table of events. No working
table to display at the moment so I added a loader as a placeholder.
Change-Id: I57fdcf0c36daf376c534a4f2aaf52fc3299cc51d
=> AdminEvents: Added Edit Events Section

js/src/patina/components/Footer.module.css, js/src/patina/components/Footer.tsx
TEST=manual
Change-Id: I7b58c0b7515d313a9dd1851f0d4ca65cf197bbb5
=> Footer: Add 501(c)(3) status

js/src/patina/components/Footer.module.css, js/src/patina/components/Footer.tsx, js/src/patina/pages/volunteer/Volunteer.page.tsx
TEST=manual
Change-Id: Ib0adff4fef7069e04b6264ce3f8c1b488ca482e7
=> Volunteer: Hide filled roles

js/src/patina/components/Footer.module.css, js/src/patina/components/Footer.tsx, js/src/patina/pages/about/mission/PillarsSection.module.css, js/src/patina/pages/volunteer/Volunteer.page.tsx
Height was too small in certain dimensions
TEST=manual
Change-Id: Ib9c8ce18e0911033b46c46b34a253d8f17087270
=> Mission: Fix text cutting out

js/src/patina/assets/images.ts, js/src/patina/pages/about/team/teamData.ts
TEST=manual
Change-Id: I3ac1f3eb8587b67692cdcde09cb5f2eb25589294
=> Team: Update board members

js/src/patina/pages/mentor-sp25/Mentor.page.tsx, js/src/patina/pages/mentorship-sp25/Mentorship.page.tsx
TEST=manual
Buttons on page lead to the right page.
Change-Id: Ie500c088e8d4c14f5ad3043eb4d5d141f73b55d9
=> Mentorship: Update Google Form Links

js/src/patina/pages/mentor-sp25/Mentor.page.tsx, js/src/patina/pages/mentor-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-sp25/Mentorship.page.tsx, js/src/patina/pages/mentorship-sp25/program/ProgramDetails.tsx
TEST=manual
Change-Id: I7013531991a7eaf38fe3d28f9a8c6e85f41909bc
=> Mentorship: Update dates and wording

js/src/patina/pages/mentor-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentor-sp25/tracks/Tracks.module.css, js/src/patina/pages/mentor-sp25/tracks/Tracks.tsx, js/src/patina/pages/mentorship-sp25/Mentorship.page.tsx, js/src/patina/pages/mentorship-sp25/about/About.tsx, js/src/patina/pages/mentorship-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-sp25/tracks/Tracks.module.css, js/src/patina/pages/mentorship-sp25/tracks/Tracks.tsx
TEST=manual
Change-Id: I0ce16c1a3576fe33426f95ed0794934cfd6bf867
=> Mentorship: Update wording

js/src/patina/Patina.routes.tsx, js/src/patina/pages/mentor-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentor-sp25/tracks/Tracks.module.css, js/src/patina/pages/mentor-sp25/tracks/Tracks.tsx, js/src/patina/pages/mentorship-sp25/Mentorship.page.tsx, js/src/patina/pages/mentorship-sp25/about/About.tsx, js/src/patina/pages/mentorship-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-sp25/tracks/Tracks.module.css, js/src/patina/pages/mentorship-sp25/tracks/Tracks.tsx
Have /mentorship and /mentor routes point to new semester.
TEST=manual
Checked all four routes.
Change-Id: I26d647e976b1578befde2677f4c27f5bd55fccd4
=> Mentorship: Swap routes

js/src/patina/pages/mentor-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-sp25/program/ProgramDetails.tsx
TEST=manual
Change-Id: I95b54633688b8826ac0f42ffd3bcb3e822c3e525
=> Mentorship: Add free food!

js/src/patina/pages/mentor-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-sp25/program/ProgramDetails.tsx
TEST=manual
Change-Id: I4bb1e1fa9a3d02e6420af97eacbd2b3741a7bbbd
=> Mentorship: Update Times and Hours

build.gradle.kts, src/main/java/org/patinanetwork/discordbot/JDAEventListener.java, src/main/java/org/patinanetwork/discordbot/JDAInitializer.java, src/main/java/org/patinanetwork/discordbot/JDAProperties.java, src/main/resources/application.properties
Use JDA to create a discord bot inside of Spring.
https://jda.wiki/using-jda/getting-started/
TEST=manual
Ran say command in test discord server and it worked
Change-Id: I748c1f90a6f681ec690c6ccb71a58560ba963a4d
=> DiscordBot: Initialize discord bot

src/main/java/org/patinanetwork/patchats/PatChatServer.java, src/main/java/org/patinanetwork/patchats/ops/DeletePatChatMemberOp.java, src/main/java/org/patinanetwork/patchats/patchats.proto, src/main/java/org/patinanetwork/patchats/repo/PatChatRepo.java, src/main/java/org/patinanetwork/patchats/repo/PsqlPatChatRepo.java
TEST=manual
localhost:8080/api/patchats/delete/1 returns JSON
Change-Id: If7245a6370180bc7129c5c749d4345c495dd33cc
=> PatChats: Add DELETE endpoint for deleting members

src/main/java/org/patinanetwork/patchats/PatChatServer.java, src/main/java/org/patinanetwork/patchats/ops/AddPatChatMemberOp.java, src/main/java/org/patinanetwork/patchats/patchats.proto, src/main/java/org/patinanetwork/patchats/repo/PatChatRepo.java, src/main/java/org/patinanetwork/patchats/repo/PsqlPatChatRepo.java
TEST=manual
http://localhost:8080/api/patchats/addmember returns JSON
Change-Id: Ifb2630ed25bf81d520abe6dc79ee121c04511204
=> PatChats: Add ADD endpoint for adding members

js/src/patina/pages/mentor-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentor-sp25/tracks/Tracks.tsx, js/src/patina/pages/mentorship-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-sp25/tracks/Tracks.tsx
TEST=manual
Change-Id: I66e7bee48ebfd7e2b0dc645a5ebc301727ac8078
=> Mentorship: Edit dates and wording

build.gradle.kts
TEST=manual
Works on my computer now, but the issue wasn't from the version
Change-Id: I0c2c91f4b233a68d9c6fa6e5bda9b8aa0d016966
=> Java: Bump palantir-java-format plugin version

src/main/java/org/patinanetwork/patchats/PatChatClient.java, src/main/java/org/patinanetwork/patchats/PatChatController.java, src/main/java/org/patinanetwork/patchats/ops/LeavePatChatMemberOp.java, src/main/java/org/patinanetwork/patchats/patchats.proto, src/main/java/org/patinanetwork/patchats/repo/PatChatRepo.java, src/main/java/org/patinanetwork/patchats/repo/PsqlPatChatRepo.java
Updated leavepatchats class, api call, endpoint, proto,
and created Op file.
TEST=manual
Change-Id: I6dc21ee6ab2290d5e61fa82b47829234cc30c531
=> PatChats: Added leave pat chats function

src/main/java/org/patinanetwork/patchats/PatChatController.java, src/main/java/org/patinanetwork/patchats/ops/MatchPatChatMemberOp.java, src/main/java/org/patinanetwork/patchats/patchats.proto
TEST=manual
localhost:8080/api/patchats/match/1 returns JSON
Change-Id: I468ae488a7b5e6f760521830c77fe3e47ea7e751
=> PatChats: Added random matching endpoint

src/main/java/org/patinanetwork/discordbot/discord.proto, src/main/java/org/patinanetwork/discordbot/repo/DiscordUserRepo.java, src/main/java/org/patinanetwork/discordbot/repo/PsqlDiscordUserRepo.java
Re-added discord user repo and template for psql repo files into
discordbot folder and created a proto file for it.
TEST=manual
- Proto file generated correctly
Edit: Resolved comments for previous push
Change-Id: I8a07ebf22a1a02914d8792e138c67489849f1097
=> PatChats: Discord User files + proto

src/main/java/org/patinanetwork/discordbot/DiscordUserController.java, src/main/java/org/patinanetwork/discordbot/ops/GetDiscordUserOp.java, src/main/java/org/patinanetwork/discordbot/ops/ListDiscordUserOp.java, src/main/java/org/patinanetwork/discordbot/repo/PsqlDiscordUserRepo.java
TEST=manual
localhost:8080/api/discord/1
and
localhost:8080/api/discord/users
return JSON
Change-Id: I846e89aee49108dca4f129b63d3b1f43ac5914bf
=> PatChats: Added list and get endpoints for discord user table

src/main/java/org/patinanetwork/discordbot/JDAEventListener.java
Building upon the original functionality of the
command by adding a
pop up the user can interact with to submit there
full name
TEST=manual
Tested discord command tested successfully locally
Change-Id: Ib549cc30cd52960e84e9f8efa36c7f050c796009
=> PatChats: Expand on Join Patchats command

src/main/java/org/patinanetwork/discordbot/DiscordUserClient.java, src/main/java/org/patinanetwork/discordbot/DiscordUserController.java, src/main/java/org/patinanetwork/discordbot/JDAEventListener.java, src/main/java/org/patinanetwork/discordbot/discord.proto, src/main/java/org/patinanetwork/discordbot/ops/AddDiscordUserOp.java, src/main/java/org/patinanetwork/discordbot/ops/GetDiscordUserOp.java, src/main/java/org/patinanetwork/discordbot/repo/DiscordUserRepo.java, src/main/java/org/patinanetwork/discordbot/repo/PsqlDiscordUserRepo.java
If the user isn't already in the database, an
instance for the user is created in the
patchats_member table as well as the discord_user
table with the Discord information.
GetDiscordUser now retrieves information based on
Discord ID instead of PatChats ID in order to
check if the user is in the database.
TEST=manual
Works in our test discord server.
Change-Id: Ib5c517b1933fae046a978f2e4dcacff4c6d4ca68
=> PatChats: Implemented /join_patchats function

src/main/java/org/patinanetwork/discordbot/JDAEventListener.java, src/main/java/org/patinanetwork/discordbot/JDAInitializer.java
Updated JDA event listener and initializer files.
TEST=manual
Change-Id: Iae34cfbbf642f30abc4a82715684cc68dfaef87c
=> PatChats: Added slash command Leave

src/main/java/org/patinanetwork/discordbot/DiscordUserController.java, src/main/java/org/patinanetwork/discordbot/JDAInitializer.java, src/main/java/org/patinanetwork/discordbot/ops/BroadcastPatChatMatchingOp.java, src/main/java/org/patinanetwork/patchats/PatChatClient.java, src/main/java/org/patinanetwork/patchats/ops/MatchPatChatMemberOp.java
TEST=manual
Change-Id: Ife657adea5b2f15ec9f0e16e5d39ad3e4b84007d
=> Patchats: Sends people dms after matching

src/main/java/org/patinanetwork/discordbot/JDAEventListener.java, src/main/java/org/patinanetwork/discordbot/JDAInitializer.java
Implemented the function to leave the weekly patchat meeting
Change-Id: Ia125fc1880f0f8a0e8f636427c3d3ae2ce6fa9df
=> PatChat: Leave Discord Function

src/main/java/org/patinanetwork/discordbot/DiscordUserClient.java
For sake of separating frontend and backend functionality
created a operation
for broadcast in the discord client
TEST=manual
Change-Id: I8d1066a826b573720263bd9296a0afab0c412fe1
=> Patchats: create a client side op for broadcast

js/src/patina/pages/mentor-sp25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-sp25/program/ProgramDetails.tsx
TEST=none
Change-Id: I8b27a9e718d1895fa78c8843f00676edb4a2b442
=> Mentorship: Update Kickoff Time

js/src/patina/pages/about/team/Team.page.tsx, js/src/patina/pages/about/team/teamData.ts
TEST=manual
Change-Id: Ie10b2f2e447f2f99a11ce623422f27c881c6b922
=> Team: Update team info

js/src/patina/navbar/NavBar.tsx
TEST=manual
Change-Id: I382675bb8b158254824e33dadb930bb0ab406f63
=> Scholarship: Read link to navbar

js/src/patina/pages/scholarship/Scholarship.page.tsx, js/src/patina/pages/scholarship/program/ProgramDetails.tsx
TEST=manual
Change-Id: I644b611a5a4c9f4944eb1e9fc780524487051540
=> Scholarship: Extend Deadline

js/src/patina/pages/mentor-fa25/Mentor.page.tsx, js/src/patina/pages/mentor-fa25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-fa25/Mentorship.page.tsx, js/src/patina/pages/mentorship-fa25/program/ProgramDetails.tsx, js/src/patina/pages/scholarship/Scholarship.page.tsx, js/src/patina/pages/scholarship/program/ProgramDetails.tsx
TEST=manual
Change-Id: Ib857568e2fc0c02986fd8bd7ee895c7da915fa16
=> Mentorship-Fa25: Update Spring to Fall

js/src/patina/pages/mentor-fa25/Mentor.page.tsx, js/src/patina/pages/mentor-fa25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-fa25/Mentorship.page.tsx, js/src/patina/pages/mentorship-fa25/program/ProgramDetails.tsx, js/src/patina/pages/scholarship/Scholarship.page.tsx, js/src/patina/pages/scholarship/program/ProgramDetails.tsx
TEST=manual
Change-Id: I2706432aed02f024b1a8b9908206e20cb11fc74e
=> Mentorship: Update dates and mentor form

js/src/patina/pages/mentor-fa25/program/ProgramDetails.tsx, js/src/patina/pages/mentorship-fa25/program/ProgramDetails.tsx
TEST=manual
Change-Id: Id048fadf907838ec38cc911fb69c76d5b2ff9436
=> Mentor Fa'25: Update in person dates
